version: '3'
services:
  neo4j: 
    # You can find the latest version at https://hub.docker.com/_/neo4j
    image: neo4j:latest
    ports:
      - 7474:7474 #HTTP port
      - 7687:7687 # neo4j / bolt port
    volumes:
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G

# docker-compose up
# Neo4j dashboard = localhost:7474/browser/
# Connect URL = neo4j://localhost:7687
# Default Username/Password = neo4j/neo4j
