version: '3'
services:
  neo4j: 
    # You can find the latest version at https://hub.docker.com/_/neo4j at the time this was developed the latest version is 5.14.0
    image: neo4j:latest
    ports:
      - 7474:7474 # HTTP port
      - 7687:7687 # neo4j / bolt port
    volumes:
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_server_http_listen__address=:7474
      - NEO4J_server_bolt_listen__address=:7687

# docker-compose up
# Neo4j dashboard = localhost:7474/browser/
# Default Username/Password = neo4j/neo4j
