version: '3'
services:
  neo4j: 
    # You can find the latest version at https://hub.docker.com/_/neo4j
    image: neo4j:latest
    ports:
      - 7474:7474 # HTTP port  | http://localhost:7474/browser/
      - 7473:7473 # HTTPs port | https://localhost:7473/browser/
      - 7687:7687 # neo4j / bolt port
    volumes:
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
      - ./ssl/:/var/lib/neo4j/ssl/
    environment:
      # Memory
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_server_memory_heap_max__size=1G
      # Set ports
      - NEO4J_server_http_listen__address=:7474
      - NEO4J_server_https_listen__address=:7473
      - NEO4J_server_bolt_listen__address=:7687
      # Bolt SSL configuration
      - NEO4J_dbms_connector_bolt_tls__level=OPTIONAL
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=./ssl/bolt
      - NEO4J_dbms_ssl_policy_bolt_private__key=private.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      # Https SSL configuration
      - NEO4J_server_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=./ssl/https
      - NEO4J_dbms_ssl_policy_https_private__key=private.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=public.crt
      - NEO4J_dbms_ssl_policy_https_client__auth=NONE

# docker-compose up
# Default Username/Password = neo4j/neo4j
